language: cpp
sudo: required
dist: xenial
compiler:
- clang
os:
- linux
before_install:
- |
  sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-xenial
  sudo apt-get -y update
script:
- |
  CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmake-latest"
  mkdir ${CMAKE_DIR}
  cd ${CMAKE_DIR}
  wget https://github.com/Kitware/CMake/releases/download/v3.15.0/cmake-3.15.0-Linux-x86_64.tar.gz
  tar -xvf cmake-3.15.0-Linux-x86_64.tar.gz
  echo ==> export PATH="${CMAKE_DIR}/cmake-3.15.0-Linux-x86_64/bin:$PATH"
  export PATH="${CMAKE_DIR}/cmake-3.15.0-Linux-x86_64/bin:$PATH"
  echo ==> PATH = $PATH
  echo ==> LS
  ls
  cd ${TRAVIS_BUILD_DIR}
  echo ==> CMake version
  cmake --version

  sudo apt-get -y install libavformat-dev libavcodec-dev libavfilter-dev libavutil-dev libswscale-dev libswresample-dev
  sudo apt-get -y install ninja
  sudo apt-get -y install qt512-meta-minimal qt512multimedia qt512svg
  source /opt/qt512/bin/qt512-env.sh
  mkdir build
  cd build
  sudo cmake ..
  sudo make
branches:
  only:
  - travis