language: cpp
sudo: required
dist: xenial
compiler:
- clang
os:
- linux
before_install:
- |
  sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-xenial
  sudo apt-get -y update
script:
- |
  wget https://cmake.org/files/v3.11/cmake-3.11.0.tar.gz
  tar -zxvf cmake-3.11.0.tar.gz
  cd cmake-3.11.0
  ./bootstrap
  make
  sudo make install
  cmake --version

  sudo apt-get -y install libavformat-dev libavcodec-dev libavfilter-dev libavutil-dev libswscale-dev libswresample-dev
  sudo apt-get -y install cmake
  sudo apt-get -y install ninja
  sudo apt-get -y install qt512-meta-minimal qt512multimedia qt512svg
  source /opt/qt512/bin/qt512-env.sh
  mkdir build
  cd build
  sudo cmake ..
  sudo make
branches:
  only:
  - travis